# - platform: template
#     sensors:
#       battery_bedroom_switch:
#         friendly_name: 'Bedroom Switch'
#         value_template: "{{ states.binary_sensor.switch_158d000110356c.attributes.battery_level|default(-1)|int if states.binary_sensor.switch_158d000110356c is not none }}"
#         unit_of_measurement: '%'
#         icon_template: '{% if states.binary_sensor.switch_158d000110356c.attributes.battery_level == 100 %}
#                            mdi:battery
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 90 %}
#                            mdi:battery-90
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 80 %}
#                            mdi:battery-80
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 70 %}
#                            mdi:battery-70
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 60 %}
#                            mdi:battery-60
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 50 %}
#                            mdi:battery-50
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 40 %}
#                            mdi:battery-40
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 30 %}
#                            mdi:battery-30
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 20 %}
#                            mdi:battery-20
#                         {% elif states.binary_sensor.switch_158d000110356c.attributes.battery_level >= 10 %}
#                            mdi:battery-10
#                         {% else %}
#                            battery-outline
#                         {% endif %}'

- platform: template
  sensors:
    battery_door:
      friendly_name: Батарейка датчик открытия двери
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001840154', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.door_window_sensor_158d0001840154.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xod1 = states.binary_sensor.door_window_sensor_158d0001840154.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.door_window_sensor_158d0001840154', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'

- platform: template
  sensors:
    battery_water_1:
      friendly_name: Батарейка датчик воды 1
      value_template: >
        {% if is_state('binary_sensor.water_leak_sensor_158d0001d72deb', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.water_leak_sensor_158d0001d72deb.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xod1 = states.binary_sensor.water_leak_sensor_158d0001d72deb.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.water_leak_sensor_158d0001d72deb', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'

- platform: template
  sensors:
    battery_water_2:
      friendly_name: Батарейка датчик воды 2
      value_template: >
        {% if is_state('binary_sensor.water_leak_sensor_158d0001d78dda', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.water_leak_sensor_158d0001d78dda.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xod1 = states.binary_sensor.water_leak_sensor_158d0001d78dda.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.water_leak_sensor_158d0001d78dda', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'