- platform: google_travel_time
  name: home to work car
  api_key: !secret google_api
  origin: !secret home_adress_waze
  destination: !secret work_adress_waze
  options:
    mode: driving

- platform: google_travel_time
  name: work to home car
  api_key: !secret google_api
  origin: !secret work_adress_waze
  destination: !secret home_adress_waze
  options:
    mode: driving

- platform: google_travel_time
  name: home to work bus
  api_key: !secret google_api
  origin: !secret home_adress_waze
  destination: !secret work_adress_waze
  options:
    mode: transit 

- platform: google_travel_time
  name: work to home bus
  api_key: !secret google_api
  origin: !secret work_adress_waze
  destination: !secret home_adress_waze
  options:
    mode: transit 

- platform: google_travel_time
  name: Phone To Home
  api_key: !secret google_api
  origin: device_tracker.iphone_pavel
  destination: !secret home_adress_waze

- platform: waze_travel_time
  name: work to home car waze
  origin: !secret work_adress_waze
  destination: !secret home_adress_waze
  region: 'EU'

- platform: waze_travel_time
  name: home to work car waze
  origin: !secret home_adress_waze
  destination: !secret work_adress_waze
  region: 'EU'