

- alias: 'All leave home'
  trigger:
    platform: state
    entity_id: group.bt_trackers
    to: 'not_home'
  action:
     - service: notify.telegram
       data:
        message: 'Все ушли из дома. Выключаем свет.'
     - service: script.turn_on
       entity_id: script.turn_off_all_lights

#Павел ушел с работы
- alias: Pavel leave work
  trigger:
    - platform: state
      entity_id: device_tracker.iphone_pavel
      from: 'Work'
      to: 'not_home'
  condition:
    - condition: time
      after: '16:30'
      before: '22:00'
  action:
     - service: notify.telegram
       data:
        message: 'Павлик ушел с работы.'


- alias: 'All arrive in sosnovka'
  trigger:
    platform: state
    entity_id: group.app_trackers
    to: 'Sosnovka'
  action:
     - service: notify.telegram
       data:
        message: 'Хорошо отдохнуть!'

- alias: 'Vacuum ON'
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    to: 'on'
  action:
     - service: notify.telegram
       data:
        message: 'Георгий начал уборку'

- alias: 'Vacuum OFF'
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    to: 'off'
  action:
     - service: notify.telegram
       data:
        message: 'Георгий завершил уборку'
 
#xiaomi switches

- alias: XSwitch computer click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001560e5a
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.YeeBigRoom

- alias: XSwitch computer double click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001560e5a
      click_type: double
  action:
    # - service: remote.send_command
    #   entity_id: 'remote.xiaomi_miio_192_168_1_57'
    #   data:
    #     command:
    #       - 'raw:Z6VjAEcCAACYAgAAxAYAAMMRAABsIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ICAAEAAAACAAICAAAAAAAAAAIAAAAAAAACAAACAgIAAAAAAAAAAAAAAAAAAAAAAAAA=='
    # - delay: 00:00:05
    # - service: remote.send_command
    #   entity_id: 'remote.xiaomi_miio_192_168_1_57'
    #   data:
    #     command:
    #       - 'raw:Z6VjACQCAABKAgAAwwYAAM8RAABfIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ISEQERARECERISAREBEQERAREBEQERARECEQESAhEBEQERAREBEQERAREBEQERARAA=='
    # - delay: 00:00:01
    - service: input_boolean.toggle
      data:
        entity_id: input_boolean.thermobool


- alias: XSwitch computer long press
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001560e5a
      click_type: long_click_press
  action:
    - service: light.toggle
      entity_id: light.YeeBigRoom

#ЗВОНОК#
- alias: DoorBell ON
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a6676b
      click_type: single
  condition:
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
  action:
     - service: xiaomi_aqara.play_ringtone
       data:
        gw_mac: F0:B4:29:CC:3E:A7
        ringtone_id: 10
        ringtone_vol: 80
     - service: tts.google_say
       entity_id: media_player.google_home
       data:
        message: 'Звонят в дверь'
     - service: notify.telegram
       data:
        message: 'Кто-то звонит в дверь'

#ЗВОНОК#
- alias: DoorBell OFF
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a6676b
      click_type: single
  condition:
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'on'
  action:
     - service: xiaomi_aqara.play_ringtone
       data:
        gw_mac: F0:B4:29:CC:3E:A7
        ringtone_id: 10
        ringtone_vol: 4
     - service: notify.telegram
       data:
        message: 'Кто-то звонит в дверь'


- alias: disable_doorbell_autoOn
  trigger:
      platform: state
      entity_id: input_boolean.disable_doorbell
      to: 'on'
  action:
      - service: notify.telegram
        data:
         message: 'Дверной звонок перевед в тихий режим'
      - delay:
          minutes: 180
      - service: homeassistant.turn_off
        entity_id: input_boolean.disable_doorbell

- alias: disable_doorbell_432432
  trigger:
      platform: state
      entity_id: input_boolean.disable_doorbell
      to: 'off'
  action:
      - service: notify.telegram
        data:
         message: 'Дверной звонок вернулся в обычный режим'


#КНОПКА У ВЫХОДА#
- alias: Exit button Vacuum on
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000113cc10
      click_type: single
  action:
    - service: vacuum.toggle
      entity_id: vacuum.xiaomi_vacuum_cleaner

- alias: telegram test at 10:00
  trigger:
    platform: time
    at: '10:00:00'
  action:
   - service: notify.telegram
     data:
      message: 'Утренняя проверка работоспособности telegram '

- alias: 'Rainy Day'
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'rain'
  condition:
    - condition: time
      after: '08:00'
      before: '23:00'
  action:
   - service: notify.telegram
     data:
      message: 'Кажется, дождик начался...'


# - alias: 'Update config if travis build is successfull'
#   trigger:
#     platform: state
#     entity_id: sensor.gurskiyhomeassistant_last_build_state
#     to: 'passed'
#   action:
#     # - service: script.get_latest_config
#     - service: notify.telegram
#       data:
#        message: 'Travis успешно собрал проект, делаем git pull и перезагружаемся'
#     - service: shell_command.git_pull
#     - service: homeassistant.restart
#     # - service: shell_command.restart_homeassistant


# - alias: "Startup Notification"
#   trigger:
#     platform: event
#     event_type: homeassistant_start
#   action:
#     - service: notify.telegram
#       data:
#        message: 'Home assistant перезагрузился'

- alias: 'Update config if travis build is successfull'
  trigger:
    platform: state
    entity_id: sensor.gurskiyhomeassistant_last_build_state
    to: 'passed'
  action:
    - service: script.restart_hass

- alias: "Startup Notification"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.telegram
      data:
       message: 'Home assistant перезагрузился'