- alias: Front Door 
  trigger:
     - platform: state
       entity_id: binary_sensor.door_window_sensor_158d0001840154
       to: 'on'
     - platform: state
       entity_id: binary_sensor.door_window_sensor_158d0001840154
       to: 'off'
  action:
     - service: notify.telegram
       data:
        message: >
          {% if is_state("binary_sensor.door_window_sensor_158d0001840154", "on") %}
            Входная дверь открыта
          {% elif is_state("binary_sensor.door_window_sensor_158d0001840154", "off") %}
            Входная дверь закрыта
          {% else %}
          {% endif %}
