- alias: Morning Rule
  trigger:
  - platform: time
    at: "08:00:00"
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
  - service: notify.telegram
    data:
     message:  |
         Доброе утро! 
         {% set day = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"] %}
         {%- set month = ["Января", "Февраля", "Марта", "Апреля", "Мая", "Июня", "Июля", "Августа", "Сентября", "Октября", "Ноября", "Декабря"] -%}
         {%- set day_della_settimana = day[now().weekday()] -%}
         {%- set month = month[now().month - 1] -%}
         Сегодня {{ day_della_settimana.lower() }} {{ now().day }} {{ month.lower() }}.  
         Сейчас {{states.sensor.dark_sky_summary.state.lower()}} и {{states.sensor.dark_sky_temperature.state|round}} градусов.
         Сегодня будет {{states.sensor.dark_sky_hourly_summary.state.lower()|replace(".", "")}},
         максимальная температура: {{states.sensor.dark_sky_daytime_high_temperature.state|round}}, минимальная температура: {{states.sensor.dark_sky_overnight_low_temperature.state|round}}.
         Шанс, что сегодня будет дождь: {{states.sensor.dark_sky_precip_probability.state | int(0)}}%.
         {% if now().strftime("%a") == 'Tue' or now().strftime("%a") == 'Wed' or now().strftime("%a") == 'Thu' %}Приблизительное время до работы на машине: {{states.sensor.home_to_work_car.state}} минуты.{% endif %}
  - condition: state
    entity_id: binary_sensor.bedroom_door
    state: 'on'
