- alias: Set GA Volume To Low At Night
  trigger:
    platform: time
    hours: 20
    minutes: 30
    seconds: 0
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home
      volume_level: 0.50

- alias: Set GA Volume To High Daytime
  trigger:
    platform: time
    hours: 9
    minutes: 0
    seconds: 0
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home
      volume_level: 0.75
