- alias: Set GA Volume To Low At Night
  trigger:
    platform: time
    hours: 20
    minutes: 30
    seconds: 0
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home
        volume_level: 0.20
    - service: notify.log
      data:
       message: 'Google home громкость на 20%'

- alias: Set GA Volume To High Daytime
  trigger:
    platform: time
    hours: 9
    minutes: 0
    seconds: 0
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home
        volume_level: 0.75
    - service: notify.log
      data:
       message: 'Google home громкость на 75%'

#- alias: Keep Google Home Alive
#  trigger:
#    platform: time
#    minutes: '/2'
#    seconds: 00
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: media_player.google_home_minis
#        state: 'off'
#      - condition: state
#        entity_id: media_player.google_home_minis
#        state: 'idle'
#  action:
#    service: media_player.play_media
#    entity_id: media_player.google_home_minis
#    data:
#      media_content_id: http://192.168.0.24/audio1sec.mp3
#      media_content_type: music