
# - alias: 'All leave home'
#   trigger:
#     platform: state
#     entity_id: group.bt_trackers
#     to: 'not_home'
#   action:
#      - service: notify.telegram
#        data:
#         message: 'Все ушли из дома. Выключаем свет.'
#      - service: script.turn_on
#        entity_id: script.turn_off_all_lights

- alias: 'All leave home'
  trigger:
    platform: state
    entity_id: group.bt_trackers
    to: 'not_home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
     - service: notify.telegram
       data:
        message: 'Все ушли из дома. Выключаем свет.'
    #  - service: script.turn_on
    #    entity_id: script.turn_off_all_lights
     - service: light.turn_off
       entity_id: light.gateway_light_f0b429cc3ea7
     - service: light.turn_off
       entity_id: light.yeebedroom
     - service: light.turn_off
       entity_id: light.yeebigroom
     - service: switch.turn_off
       entity_id: switch.wall_switch_158d00014ddc4f
     - service: switch.turn_off
       entity_id: switch.wall_switch_left_158d00012bad35
     - service: switch.turn_off
       entity_id: switch.wall_switch_right_158d00012bad35
       
- alias: Pavel leave work
  trigger:
    - platform: state
      entity_id: device_tracker.iphone_pavel
      from: 'Work'
      to: 'not_home'
  condition:
    - condition: time
      after: '16:30'
      before: '22:00'
  action:
     - service: notify.telegram
       data:
      #  message: 'Павлик ушел с работы. Приблизительное время прибытия: {{(as_timestamp(now()) + (states.sensor.work_to_home_bus.state | default(0) | int)*60) | timestamp_custom("%H:%M")}}'
        message: >-
          {% if is_state('input_boolean.from_work_on_auto', 'off') %}
            'Павлик ушел с работы. Едет на общественном транспорте. Приблизительное время прибытия: {{(as_timestamp(now()) + (states.sensor.work_to_home_bus.state | default(0) | int)*60) | timestamp_custom("%H:%M")}}'   
          {% elif is_state('input_boolean.from_work_on_auto', 'on') %}
            'Павлик ушел с работы. Едет на машине. Приблизительное время прибытия: {{(as_timestamp(now()) + (states.sensor.work_to_home_car_waze.state | default(0) | int)*60) | timestamp_custom("%H:%M")}}'   
          {% endif %}
     - condition: state
       entity_id: input_boolean.disable_doorbell
       state: 'off'
     - service: tts.yandextts_say
       entity_id: media_player.google_home
       data_template:
         message: >
          {% if is_state('input_boolean.from_work_on_auto', 'off') %}
            Павлик ушел с работы. Едет на общественном транспорте. Приблизительное время прибытия: {{(as_timestamp(now()) + (states.sensor.work_to_home_bus.state | default(0) | int)*60) | timestamp_custom("%H:%M")}} 
          {% elif is_state('input_boolean.from_work_on_auto', 'on') %}
            Павлик ушел с работы. Едет на машине. Приблизительное время прибытия: {{(as_timestamp(now()) + (states.sensor.work_to_home_car.state | default(0) | int)*60) | timestamp_custom("%H:%M")}}
          {% endif %}
        

- alias: 'All arrive in sosnovka'
  trigger:
    platform: state
    entity_id: group.app_trackers
    to: 'Sosnovka'
  action:
     - service: notify.telegram
       data:
        message: 'Хорошо отдохнуть!'


  #condition:
  #  - condition: template
  #    value_template: '{{ states.device_tracker.1.state != "home"}}'
  #  - condition: template
  #    value_template: '{{ states.device_tracker.2.state != "home"}}'